# -*- coding: utf-8 -*-
"""spectrogramnew.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ufrww_8BCuudEiKOA8Yt8rUZxQ2y0eNH
"""

import scipy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv("/content/drive/MyDrive/S26G4AllChannels.csv")

d1=data['FC6']

samplingfrequency=400
powerSpectrum, freqenciesFound, time, imageAxis = plt.specgram(d1, Fs=samplingfrequency)

